server:
  port: 10086

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# sl4j 打印相关配置
logging:
  file:
    path: d:/log/tailf
  level:
    com.xx.log: debug

tailf:
  # 第一次进入页面默认获取的日志行数
  default-show-line-num: 100

  # 监听目录，可以设置多个以 ; 隔开
  monitor-path: D:/log/log01;D:/log/log02

  # 当前应用的角色（master|slave）
  web-role: master

  # master netty IP（配置成内网IP,master-slave模式会使用该配置）
  master-netty-host: 127.0.0.1

  # master netty port（master-slave模式会使用该配置，为空时不启动netty server）
  master-netty-port: 10085

  # 日志文件读取时使用的文件编码
  log_file_encoding: utf-8

  deploy:
    # 自动部署时附件文件所在的目录
    attachment-file-path: e:/repository/org/example/tailf-web/1.2.0-SNAPSHOT/

    # 自动部署时附件文件的名称(注意：该配置要与上面的 attachment-file-path 能组成正确的文件路径)
    attachment-file-name: tailf-web-1.2.0-SNAPSHOT.jar
